In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv(r"C:\Users\esami\ML 100days\zomato.csv")
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [11]:
df.shape

(51717, 17)

In [13]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [35]:
df.drop(['url', 'address','dish_liked','phone', 'menu_item', 'reviews_list'], axis = 1, inplace = True)
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  object
 1   online_order                 51717 non-null  object
 2   book_table                   51717 non-null  object
 3   rate                         43942 non-null  object
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  object
 6   rest_type                    51490 non-null  object
 7   cuisines                     51672 non-null  object
 8   approx_cost(for two people)  51371 non-null  object
 9   listed_in(type)              51717 non-null  object
 10  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(10)
memory usage: 4.3+ MB

In [39]:
duplicates = df[df.duplicated()]
print(duplicates)

                            name online_order book_table    rate  votes  \
596                 My Tea House          Yes        Yes     NEW      0
2235                  Shiv Sagar           No         No   3.6/5     10
3763       The Fisherman's Wharf          Yes        Yes   4.4/5   4099
4339               Biryani Treat           No         No     NaN      0
4949                   OPUS Club           No        Yes   4.4/5   1496
...                          ...          ...        ...     ...    ...
49193  Sri Ganesh Juice Junction          Yes         No  3.5 /5      6
49432              Biryani Treat           No         No     NaN      0
50379             House Of Candy          Yes         No     NaN      0
50405             House Of Candy          Yes         No     NaN      0
50904           Nawab Di Biryani          Yes         No     NEW      0

                location           rest_type  \
596         Banashankari       Casual Dining
2235   Bannerghatta Road          Food Court
3763       Sarjapur Road  Casual Dining, Bar
4339           Bellandur         Quick Bites
4949       Sarjapur Road                 Pub
...                  ...                 ...
49193          Bellandur       Beverage Shop
49432          Bellandur         Quick Bites
50379         Whitefield       Confectionery
50405         Whitefield       Confectionery
50904         Whitefield  Takeaway, Delivery

                                              cuisines  \
596              Continental, Asian, North Indian, Tea
2235                           South Indian, Beverages
3763   Seafood, Goan, North Indian, Continental, Asian
4339                                           Biryani
4949       Continental, Italian, North Indian, Mexican
...                                                ...
49193                                Juices, Fast Food
49432                                          Biryani
50379                                         Desserts
50405                                         Desserts
50904                                 Biryani, Mughlai

      approx_cost(for two people)     listed_in(type)    listed_in(city)
596                           500            Dine-out       Banashankari
2235                          400            Dine-out  Bannerghatta Road
3763                        1,400              Buffet          Bellandur
4339                          400            Delivery          Bellandur
4949                        1,900  Drinks & nightlife          Bellandur
...                           ...                 ...                ...
49193                         200            Delivery      Sarjapur Road
49432                         400            Delivery      Sarjapur Road
50379                         200            Delivery         Whitefield
50405                         200            Delivery         Whitefield
50904                         400            Delivery         Whitefield

[108 rows x 11 columns]

In [31]:
df.drop_duplicates(inplace = True)

In [33]:
df.shape

(51717, 17)